"""Initial migration

Revision ID: 0bce4bb9c0bf
Revises: 
Create Date: 2024-03-07 01:24:04.844643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bce4bb9c0bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'admin_sign_up_token', 'admin', ['added_by'], ['id'])
    op.create_foreign_key(None, 'community_messages', 'community', ['community_id'], ['id'])
    op.alter_column('farms', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('farms', 'method',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('farms', 'services',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('farms', 'farm_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('farms', 'method_description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('farms_farmer_id_fkey', 'farms', type_='foreignkey')
    op.create_foreign_key(None, 'farms', 'modelfarmers', ['farmer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.create_foreign_key('farms_farmer_id_fkey', 'farms', 'farmers', ['farmer_id'], ['id'])
    op.alter_column('farms', 'method_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('farms', 'farm_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('farms', 'services',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('farms', 'method',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('farms', 'name',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'community_messages', type_='foreignkey')
    op.drop_constraint(None, 'admin_sign_up_token', type_='foreignkey')
    # ### end Alembic commands ###
